# Generated by Django 5.0.3 on 2024-04-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='breed',
            name='size',
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(max_length=1),
        ),
        migrations.AddConstraint(
            model_name='breed',
            constraint=models.CheckConstraint(check=models.Q(('size__in', ['Small', 'Tiny', 'Medium', 'Large'])), name='size'),
        ),
    ]
