# Generated by Django 5.0.3 on 2024-04-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_remove_breed_size_alter_breed_size_breed_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('Small', 'S'), ('Tiny', 'T'), ('Medium', 'M'), ('Large', 'L')], max_length=10),
        ),
    ]
